# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "library-cookbook", "~> 0.1.0", git: "https://github.com/vacovsky/tinkering_with_opsworks.git", rel: "tinkering-with-opsworks"
